;;; customization --- keeps theme configuration and fonts
;;; Commentary:
;;; Code:
(add-to-list 'default-frame-alist '(fullscreen . maximized))

(set-frame-font (font-spec
		 :family "Terminess Nerd Font Mono"
		 :name "Terminess Nerd Font Mono"
		 :size 32) nil t)
;; (set-frame-font (font-spec :family "Droid Sans Mono" :size 22) nil t)

;; (set-face-foreground 'mode-line                                     "black")
;; (set-face-background 'mode-line                                     "silver")
;; (set-face-background 'mode-line-inactive                            "grey15")
;; (set-face-foreground 'mode-line-inactive                            "grey")
;; (set-foreground-color                                               "burlywood3")
;; (set-background-color                                               "#1d2021")
;; (set-cursor-color                                                   "burlywood3")
;; (set-face-attribute 'font-lock-builtin-face nil :foreground         "#DAB98F")
;; (set-face-attribute 'font-lock-comment-face nil :foreground         "gray50")
;; (set-face-attribute 'font-lock-constant-face nil :foreground        "DarkGoldenrod")
;; (set-face-attribute 'font-lock-doc-face nil :foreground             "gray50")
;; (set-face-attribute 'font-lock-function-name-face nil :foreground   "burlywood3")
;; (set-face-attribute 'font-lock-keyword-face nil :foreground         "DarkGoldenrod")
;; (set-face-attribute 'font-lock-string-face nil :foreground          "olive drab")
;; (set-face-attribute 'font-lock-type-face nil :foreground            "cyan4")
;; (set-face-attribute 'font-lock-variable-name-face nil :foreground   "burlywood3")

(setq-default truncate-lines t)
(setq truncate-partial-width-windows nil)
(setq next-line-add-newlines nil)
(setq inhibit-splash-screen t)
(setq inhibit-startup-message t)
(setq use-dialog-box nil)
(setq redisplay-dont-pause t)
(setq ring-bell-function 'ignore)
(setq undo-limit 20000000)
(setq undo-strong-limit 40000000)
(setq scroll-step 1)
(setq default-tab-size 4)
(setq default-offset 4)

;; till i don't check time in status bar
;; (interactive)
;; (setq display-time-day-and-date 1)
;; (setq display-time-format "%A %d.%m.%y %H:%M")
;; (display-time)

(tooltip-mode        -1)
(menu-bar-mode       -1)
(tool-bar-mode       -1)
(scroll-bar-mode     -1)
(blink-cursor-mode   -1)
(global-hl-line-mode  1)
(column-number-mode   1)

(set-face-background 'hl-line "grey18")

(delete-selection-mode t)

(use-package ivy)
(use-package swiper)
(use-package counsel)
(ivy-mode 1)
(setq ivy-use-virtual-buffers t)
(setq enable-recursive-minibuffers t)
(global-set-key "\C-s" 'swiper)
(global-set-key (kbd "C-c C-r") 'ivy-resume)
(global-set-key (kbd "<f6>") 'ivy-resume)
(global-set-key (kbd "M-x") 'counsel-M-x)
(global-set-key (kbd "C-x C-f") 'counsel-find-file)
(global-set-key (kbd "<f1> f") 'counsel-describe-function)
(global-set-key (kbd "<f1> v") 'counsel-describe-variable)
(global-set-key (kbd "<f1> l") 'counsel-find-library)
(global-set-key (kbd "<f2> i") 'counsel-info-lookup-symbol)
(global-set-key (kbd "<f2> u") 'counsel-unicode-char)
(global-set-key (kbd "C-c g") 'counsel-git)
(global-set-key (kbd "C-c j") 'counsel-git-grep)
(global-set-key (kbd "C-c k") 'counsel-ag)
(global-set-key (kbd "C-x l") 'counsel-locate)
(global-set-key (kbd "C-S-o") 'counsel-rhythmbox)
(define-key minibuffer-local-map (kbd "C-r") 'counsel-minibuffer-history)
(icomplete-mode 1)
